# Generated by Django 5.1.2 on 2025-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cor", "0002_alter_entry_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="romanization",
            field=models.TextField(
                blank=True,
                default="",
                help_text="optional transliteration (e.g. pīnyīn for 中文)",
            ),
        ),
    ]
